# order-service | sit environment
server.port=8080
server.servlet.context-path=/orders
spring.profiles.active=sit
spring.application.name=order-service
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
logging.level.root=INFO
logging.level.com.example.order=DEBUG
spring.datasource.url=jdbc:postgresql://postgres-sit.order-service-sit.svc:5432/orderdb
spring.datasource.username=order_user
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
order.payment-service.url=http://payment-service.payment-service-sit.svc:8080/payment
order.inventory-service.url=http://inventory-service.inventory-sit.svc:8080
order.max-items-per-order=50
order.feature.express-delivery=true
